In [1]:
import numpy as np

In [74]:
a = np.array([
    [[1,2],[3,4]],
    [[5,7],[9,11]],
    [[13,15],[17,19]],
])
print(a)
print(a[0])

[[[ 1  2]
  [ 3  4]]

 [[ 5  7]
  [ 9 11]]

 [[13 15]
  [17 19]]]
[[1 2]
 [3 4]]


In [55]:
def f(v):
    print(v)

np.apply_along_axis(f, 0, a)

[ 1  5 13]
[ 2  7 15]
[ 3  9 17]
[ 4 11 19]


array([[None, None],
       [None, None]], dtype=object)

In [61]:
for v in a:
    print("row",v)

row [[1 2]
 [3 4]]
row [[ 5  7]
 [ 9 11]]
row [[13 15]
 [17 19]]


In [62]:
f = lambda x: x + 1
b = np.array([f(xi) for xi in a])
print(b)

[[[ 2  3]
  [ 4  5]]

 [[ 6  8]
  [10 12]]

 [[14 16]
  [18 20]]]


In [ ]:
c = np.array([
    [ 1,  2],
    [ 3,  4]
])
b = np.sum(c, axis=0)
print("sum along column", b)
b = np.sum(c, axis=1)
print("sum along row", b)

In [64]:
c = np.array([
    [ 1,  2],
    [ 3,  4]
])
print(c)
print(c[None])

[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]


In [66]:
c = np.array([
    [ 1,  2],
    [ 3,  4]
])
a = np.array([
    [5, 6]
])
b = np.append(c, a, axis=0)
print(b)
b = np.append(a, c, axis=0)
print(b)

[[1 2]
 [3 4]
 [5 6]]
[[5 6]
 [1 2]
 [3 4]]


In [68]:
c = np.array([
    [ 1,  2],
    [ 3,  4]
])
print(c)
b = np.tile(c, (5, 1, 1, 1))
print(b)

[[1 2]
 [3 4]]
[[1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4]]


In [72]:
c = np.array([
    [ 1,  2],
    [ 3,  4]
])
print(c)
b = c[None]
print(b)
b = np.squeeze(b)
print(b)

[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]
[[1 2]
 [3 4]]


In [83]:
c = np.array([
    [1,2,3,4,5],
    [6,7,8,9,0],
    [0,0,0,0,0]
])
print(c.shape)
print(*c[:2])

(3, 5)
[1 2 3 4 5] [6 7 8 9 0]
